#!/usr/bin/env python3
from pathlib import Path

path = Path("index.html")
html = path.read_text(encoding="utf-8")

old = '''          <p class="lead">An upcoming PhD student of development economics at SOAS. Graduating with the highest distinction from NUFE and a merit from the University of Edinburgh, preparing my doctoral research in the political economy of development on the micro-foundations of industrial policy and political settlements from an ideological (Žižekian) and institutional (evolutionary) perspective. Proficient in NVivo, Stata, ArcMap, Python, Matlab, open to both qualitative and quantitative methodologies, with extensive industrial and academic experience from CITIC, Mazars, Deloitte, HQSW, Duke Kunshan, NUFE, UoEdin, UoSheff, HNU, SUFE, Fudan, Bayes, and several public &amp; private organisations. Involved in a range of heterodox and evidence-based economic research on the political economy of urban &amp; international development, political settlements, informal institutions, industrial policy, transport infrastructure policy, and entrepreneurship, looking for the most and least represented local samples with diverse formal and informal institutions. Seeking more professional challenges and mission-oriented policy-relevant academic environments in international research universities where methodological and theoretical pluralism is valued to apply my knowledge of real-world economics and a transferable skill set.</p>'''

new = '''          <p class="lead">An upcoming PhD student of development economics at SOAS. Graduating with the highest distinction from NUFE and a merit from the University of Edinburgh, preparing my doctoral research in the political economy of development on the micro-foundations of industrial policy and political settlements from an ideological (Žižekian) and institutional (evolutionary) perspective. Proficient in NVivo, Stata, ArcMap, Python, Matlab, open to both qualitative &amp; quantitative methodologies, with extensive industrial and academic experience from CITIC, Mazars, Deloitte, HQSW, Duke Kunshan, NUFE, UoEdin, UoSheff, HNU, SUFE, Fudan, Bayes, several public and private organisations. Involved in a range of heterodox and evidence-based economic research on such as the political economy of urban &amp; international development, political settlements, informal institutions, industrial policy, transport infrastructure policy, and entrepreneurship alike, looking for the most and least represented local samples with diverse formal &amp; informal institutions. Seeking more professional challenges and mission-oriented policy-relevant academic environments in international research universities where methodological and theoretical pluralism is valued to apply my knowledge of real-world economics and a transferable skill set.</p>'''

count = html.count(old)
if count != 1:
    raise RuntimeError(f"Expected exactly one About paragraph match, found {count}")

path.write_text(html.replace(old, new, 1), encoding="utf-8")
