from pathlib import Path

path = Path("index.html")
text = path.read_text(encoding="utf-8")
old = """          <p class=\"lead\">A motivated individual rerum cognoscere causas graduating with the highest distinction from NUFE and a merit from the University of Edinburgh, preparing my doctoral research in the political economy of development at SOAS to study the microfoundations of industrial policy and political settlements from a Žižekian ideological and evolutionary institutional change perspective. Proficient in NVivo, Stata, ArcMap, Python and open to both qualitative &amp; quantitative methodologies, with extensive industrial and academic experience gained from CITIC, Mazars, Deloitte, HQSW, Duke Kunshan, NUFE, UoEdin, UoSheff, SUFE, Fudan, and several public &amp; private organisations. Involved in a range of heterodox and evidence-based economics research on the political economy of urban &amp; international development, political settlements framework, industrial policy, transport infrastructure policy, and entrepreneurship, looking for the most and least represented samples from localities with diverse formal and informal institutions. Committed to continuous personal development, and seeking more professional challenges in international organisations and research universities to apply my knowledge and a transferable skill set.</p>"""
new = """          <p class=\"lead\">Upcoming PhD student of development economics at SOAS. Graduating with the highest distinction from NUFE and a merit from the University of Edinburgh, preparing my doctoral research in the political economy of development on the micro-foundations of industrial policy and political settlements from an ideological (Žižekian) and institutional (evolutionary) perspective. Proficient in NVivo, Stata, ArcMap, Python, open to both qualitative &amp; quantitative methodologies, with extensive industrial and academic experience from CITIC, Mazars, Deloitte, HQSW, Duke Kunshan, NUFE, UoEdin, UoSheff, HNU, SUFE, Fudan, several public &amp; private organisations. Involved in a range of heterodox and evidence-based economic research on the political economy of urban &amp; international development, political settlements framework, industrial policy, transport infrastructure policy, and entrepreneurship, looking for the most and least represented samples from localities with diverse formal and informal institutions. Committed to continuous personal development, and seeking more professional challenges in international research universities to apply my knowledge of real-world economics and a transferable skill set.</p>"""
count = text.count(old)
if count != 1:
    raise RuntimeError(f"Expected exactly one About Tao paragraph, found {count}")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
